apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: healthcare
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: frontend
          image: frontend:latest
          imagePullPolicy: Never
          command: ["npm", "start"]
          ports:
            - containerPort: 3000
              hostPort: 3000