apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: patient-service
          image: patient-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
              hostPort: 3002
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGO_URI
              value: "mongodb+srv://nikeshala:nikeshala1234@cluster0.0gkxjkv.mongodb.net/patient_db"
            - name: JWT_SECRET
              value: "secret@2026"