apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3006
              hostPort: 3006
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGO_URI
              value: "mongodb+srv://nikeshala:nikeshala1234@cluster0.0gkxjkv.mongodb.net/payment_db"
            - name: JWT_SECRET
              value: "secret@2026"
            - name: PAYPAL_CLIENT_ID
              value: "AXKTmBczyTaYVF1IaYAYJwHjSIMyLSelxn8q_-vFSI8Htp6ifkpFIZsuF3eLILXZSFOyccnDo_lauuiV"
            - name: PAYPAL_CLIENT_SECRET
              value: "EEp6I6gh6K7XCNdvwsthBQWyU8JiHvG_vmGMpATgHQNC9HTULi98gcTx2b76Qth5NmjWmxCcgem-baKh"
            - name: PAYPAL_BASE_URL
              value: "https://api-m.sandbox.paypal.com"